#!/usr/bin/env bash
export CUDA_VISIBLE_DEVICES=0
export MLFLOW_TRACKING_URI=${MLFLOW_TRACKING_URI:-http://localhost:5000}
export MLFLOW_EXPERIMENT_NAME=${MLFLOW_EXPERIMENT_NAME:-"torch_gpu_experiment"}
echo "Environment settings:"
echo " CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES"
echo " MLFLOW_TRACKING_URI=$MLFLOW_TRACKING_URI"
echo " MLFLOW_EXPERIMENT_NAME=$MLFLOW_EXPERIMENT_NAME"
